name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.0'
        cache-dependency-path: |
          ./packages/sample/hello/go.sum
          # tools/go.sum

    - name: Test
      working-directory: ./packages/sample/hello
      run: go test -v ./...
